language: node_js

node_js:
    - "node"
    - "8"
    #- "6"
    #- "4"
    #- "0.12"
    #- "0.11"
    #- "0.10"

sudo: false

git:
    submodules: false

before_script:
    # Prepare for automated tests
    - make install

script:
    # Run tests
    - make check test

notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/402edc7d9acf917722ed
        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
