version: "3"
services:
    course:
        image: dbwebb/courserepo
        ports:
            - "10081:80"
        volumes:
            - ./:/dbwebb-kurs/
            - /dbwebb-kurs/bin/
            - /dbwebb-kurs/build/
            - /dbwebb-kurs/example/utility/
            - /dbwebb-kurs/node_modules/
            #- /dbwebb-kurs/vendor/
    mysql:
        image: mysql
        ports:
            - "13306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pass
        #volumes:
        #    - /mysql_init:/docker-entrypoint-initdb.d
