version: "3"
services:
    mariadb:
        container_name: mariadb
        image: mariadb/server:latest
        restart: always
        ports:
            - "13306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: "pass"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./sql.d:/docker-entrypoint-initdb.d

    mariadb-client:
        container_name: mariadb-client
        image: mariadb:latest

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "pass"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql.d:/docker-entrypoint-initdb.d

    mysql-client:
        container_name: mysql-client
        image: mysql:latest

volumes:
    mysql_data: {}
    mariadb_data: {}
